title: Excellent
author: Amielucha
email: amielucha@notyourbusiness.dev
description: > # this means to ignore newlines until "baseurl:"
  now for something completely different.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
